name: Java Maven Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Maven inside DavidPOO
      run: mvn clean package
      working-directory: ./DavidPOO

    - name: Upload app executable artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-executable
        path: DavidPOO/target/
