name: Java Maven Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Project
        run: |
          cd DavidPOO
          chmod +x mvnw
          ./mvnw clean package -DskipTests

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: app-executable
          path: DavidPOO/target/*.jar
