name: Java Maven Build

on:
  push:
    branches: [ "main", "dev-Sesión04" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for mvnw
        run: chmod +x DavidPOO/mvnw

      - name: Build with Maven
        working-directory: ./DavidPOO
        run: ./mvnw clean package -DskipTests

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-executable
          path: 'DavidPOO/target/*.jar'
      uses: actions/upload-artifact@v4
      with:
        name: app-executable
        path: 'DavidPOO/target/*.jar'
